[package]
name = "shared_mutex"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
libc = "0.2.174"
memmap2 = "0.9.7"
nix = { version = "0.30.1", features = ["pthread"] }

[features]
tsan = []
